// Next.js 16.3.4 (App Router). Verified against node_modules/next/dist/docs:
// - app/layout: root layout must render <html>/<body>; typed via LayoutProps<"/">
// - metadata: export a `Metadata` object (static) from layout/page
// - next/font: next/font/google self-hosts fonts, expose CSS var via `variable`
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
